### ISSUE TITLE
Easylist spanish

### ISSUE THREAD

**Issue by malopez00** [ZingyAwesome/easylists-for-pihole#10]
Would you mind adding the spanish list also? Thank you very much

**Comment by ZingyAwesome** [comment]
Sorry for the delay, can you link the filter list you want added?

**Comment by malopez00** [comment]
https://github.com/easylist/easylistspanish

**Comment by gpupu** [comment]
Hi @0Zinc , I am also interested on this. Seems list is there, but is empty. Could you provide it or, on the other hand, explain your procedure to translate easylist to domain format

Thanks in advance

**Comment by gpupu** [comment]
Just sent you a PR updating the list. Not so much experience with this, so if you consider this is not the correct method, please discard it

Thank you!

**Comment by ZingyAwesome** [comment]
I've moved all language specific lists to a new language folder (it was getting quite cluttered) and added the Spanish list properly.
