### ISSUE TITLE
EasyList-Cookie list for pihole

### ISSUE THREAD

**Issue by jbhardman** [ZingyAwesome/easylists-for-pihole#14]
What about creating a pihole compatible list from the EasyList-Cookie list that Brave uses for blocking cookie notices?

**Comment by ZingyAwesome** [comment]
Is [this](https://secure.fanboy.co.nz/fanboy-cookiemonster.txt) the one you mean?

**Comment by DarkSkull91** [comment]
I think so, it would be great!

**Comment by ZingyAwesome** [comment]
Added. I'd just like to say obviously it won't be as effective as a Brave's given that PiHole/AGH can only block DNS requests and can't do HTML element filtering.

**Comment by jbhardman** [comment]
Thank you!
