### ISSUE TITLE
Broken local development using Lando

### ISSUE THREAD

**Issue by millnut** [ZingyAwesome/easylists-for-pihole#16]
**Describe the bug**
When working on a project using Lando (https://lando.dev/) all local development domains `*.lndo.site` are blocked, this was introduced in this commit (https://github.com/ZingyAwesome/easylists-for-pihole/commit/d7eac6a88cd370eea3f7428a09d466f6a7a53b5a)

**To Reproduce**
Run any project locally using lando, you will find that the EasyPrivacy list blocks the domain.

**Expected behavior**
`*.lndo.site` are not blocked.

**Comment by ZingyAwesome** [comment]
Hello, this project just converts easylist format lists into hosts format, so DNS-level blockers like pihole and AGH can use them. I don't own or maintain any of the blocklists used, so I can't deal with false positives.

I checked this issue upstream, and it seems like it was just [dealt with](https://github.com/easylist/easylist/commit/b1791592deae3b09acd0879af8839aa4f538ccdd) by changing the block to 3rd party. DNS blockers don't understand the difference between 1st and 3rd party, so all 3rd party only blocks are removed. I've run an early update of the lists which has removed it in the latest commit.
