### ISSUE TITLE
Easylist Russia and Ukraine

### ISSUE THREAD

**Issue by neuro18** [ZingyAwesome/easylists-for-pihole#17]
Hello.

Would you mind adding the Russian and Ukrainian list as well?

Raw list:
`https://easylist-downloads.adblockplus.org/advblock.txt`

General info about the list (in Russian):
`https://forums.lanik.us/viewtopic.php?t=22512-%D0%BE-%D1%84%D0%B8%D0%BB%D1%8C%D1%82%D1%80%D0%B5-ru-adlist-%D0%B8-%D0%B4%D0%BE%D0%BF%D0%BE%D0%BB%D0%BD%D0%B5%D0%BD%D0%B8%D1%8F%D1%85`

Thank you.

**Comment by neuro18** [comment]
Also, sources for RUAdList:

`https://github.com/easylist/ruadlist`

where, as far as I understand, they compile the final list for domains mainly using these 3 files:

`advblock/first_level.txt
advblock/thirdparty.txt
advblock/adservers.txt`

**Comment by ZingyAwesome** [comment]
Added, you can find it under language/russian.txt
