### ISSUE TITLE
Help offering

### ISSUE THREAD

**Issue by yoavain** [ZingyAwesome/easylists-for-pihole#3]
Is it possible for you to share the code using for parsing the lists?
I would like to help with automations (via git actions) and adding some more locales

**Comment by ZingyAwesome** [comment]
Hello! I'll attach some code. Thanks for offering to help.
````
curl -s -L <easylist source url depending on locale>  > lists.unsorted

sort -u lists.unsorted | grep ^\|\|.*\^$ | grep -v \/ > lists.sorted

sed 's/[\*|^]//g' < lists.sorted > easylist.txt

# remove old files
rm lists.unsorted lists.sorted
```

**Comment by yoavain** [comment]
I've started working on a script that accept an `input.txt` file in this structure:
```
<source url 1>  <target file 1>
<source url 2>  <target file 2>
```
i.e.
```txt
https://raw.githubusercontent.com/easylist/easylist/master/easylist/easylist_adservers.txt  easylist.txt
https://raw.githubusercontent.com/easylist/easylist/master/easylist/easylist_adservers_popup.txt  easylist.txt
https://raw.githubusercontent.com/easylist/easylist/master/easyprivacy/easyprivacy_trackingservers.txt  easyprivacy.txt
https://raw.githubusercontent.com/easylist/easylist/master/easyprivacy/easyprivacy_trackingservers_international.txt  easyprivacy.txt
```
Script supports parsing multiple URLs into the same target file. (They will be joined & sorted)

Can you provide a file in this structure for the input you're using for each target file?
(Result I'm getting with the above input.txt are very different from your files)

Thanks!

Once I'm done with the script, I'll start with automating.

**Comment by ZingyAwesome** [comment]
Easylist:
```
https://easylist-downloads.adblockplus.org/easylist.txt https://easylist-downloads.adblockplus.org/malwaredomains_full.txt easylist.txt
```
Easyprivacy:
```
https://easylist.to/easylist/easyprivacy.txt easyprivacy.txt
```
Easylist Germany:
```
https://easylist.to/easylistgermany/easylistgermany.txt easylistgermany.txt
```
Easylist Italy
```
https://easylist-downloads.adblockplus.org/easylistitaly.txt easylistitaly.txt
```
Easylist Dutch
```
https://easylist-downloads.adblockplus.org/easylistdutch.txt easylistdutch.txt
```
Easylist France
```
https://easylist-downloads.adblockplus.org/liste_fr.txt easylistfrance.txt
```

Difference probably due to me adding malewaredomains into easylist and also I use the easylist website rather than the GitHub.

**Comment by ghost** [comment]
My statement to parse AdBlock lists:

`sort -u -f <"$source" | grep ^\|\|.*\^ | sed 's/[\|^]//g' |  grep -P '(?=^.{4,253}$)(^(?:[a-zA-Z0-9](?:(?:[a-zA-Z0-9\-]){0,61}[a-zA-Z0-9])?\.)+([a-zA-Z]{2,}|xn--[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])$)' > "$sourceout"
`
